apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cqrs-example.fullname" . }}-config
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "cqrs-example.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
