apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cqrs-example.fullname" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "cqrs-example.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "cqrs-example.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "cqrs-example.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ include "cqrs-example.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
              name: http
          envFrom:
            - configMapRef:
                name: {{ include "cqrs-example.fullname" . }}-config
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
